"""
Label type seed data
"""

LABEL_TYPES = [
    {
        "name": "FDA Vertical (Standard)",
        "code": "fda_vertical",
        "category": "regulatory",
        "description": "Standard U.S. FDA Nutrition Facts label in vertical format",
        "region": "USA",
        "languages": ["en"],
        "display_modes": ["per_serving", "per_container"],
        "daily_calorie_base": 2000,
        "energy_unit": "kcal",
        "sodium_display": "sodium",
        "default_width": 400,
        "default_height": 600,
        "is_system": True,
        "typography": {
            "fontFamily": "Helvetica, Arial, sans-serif",
            "titleFontSize": 28,
            "titleFontWeight": "900",
            "headerFontSize": 12,
            "bodyFontSize": 11,
            "footnoteSize": 8,
        },
        "border_config": {
            "width": 1,
            "color": "#000000",
            "style": "solid",
        },
        "color_scheme": {
            "background": "#ffffff",
            "text": "#000000",
            "accent": "#000000",
            "divider": "#000000",
        },
        "footnotes": [
            {
                "text": "* The % Daily Value (DV) tells you how much a nutrient in a serving of food contributes to a daily diet. 2,000 calories a day is used for general nutrition advice.",
                "textAr": "",
                "required": True,
            },
        ],
        # Nutrients to include (with config)
        "nutrients": [
            {"key": "calories", "is_mandatory": True, "show_percent_dv": False, "is_bold": True, "indent_level": 0},
            {"key": "total_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "saturated_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "trans_fat", "is_mandatory": True, "show_percent_dv": False, "is_bold": False, "indent_level": 1},
            {"key": "cholesterol", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "sodium", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "total_carbs", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "dietary_fiber", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "total_sugars", "is_mandatory": True, "show_percent_dv": False, "is_bold": False, "indent_level": 1},
            {"key": "added_sugars", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 2},
            {"key": "protein", "is_mandatory": True, "show_percent_dv": False, "is_bold": True, "indent_level": 0},
            {"key": "vitamin_d", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "calcium", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "iron", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "potassium", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
        ],
    },
    {
        "name": "GSO Bilingual Label",
        "code": "gso_bilingual",
        "category": "regulatory",
        "description": "GCC Standardization Organization compliant bilingual nutrition label (English/Arabic)",
        "region": "GCC",
        "languages": ["en", "ar"],
        "display_modes": ["per_serving", "per_100g"],
        "daily_calorie_base": 2000,
        "energy_unit": "both",  # kJ and kcal
        "sodium_display": "salt",  # GSO prefers salt over sodium
        "default_width": 450,
        "default_height": 650,
        "is_system": True,
        "typography": {
            "fontFamily": "Arial, sans-serif",
            "fontFamilyAr": "Noto Naskh Arabic, Arial, sans-serif",
            "titleFontSize": 24,
            "titleFontWeight": "bold",
            "headerFontSize": 11,
            "bodyFontSize": 10,
            "footnoteSize": 8,
        },
        "border_config": {
            "width": 2,
            "color": "#000000",
            "style": "solid",
        },
        "color_scheme": {
            "background": "#ffffff",
            "text": "#000000",
            "accent": "#000000",
            "divider": "#000000",
        },
        "footnotes": [
            {
                "text": "* Percent Daily Values are based on a 2,000 calorie diet.",
                "textAr": "* تستند القيم اليومية المئوية على نظام غذائي يحتوي على 2000 سعرة حرارية.",
                "required": True,
            },
        ],
        "nutrients": [
            {"key": "calories", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "total_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "saturated_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "trans_fat", "is_mandatory": True, "show_percent_dv": False, "is_bold": False, "indent_level": 1},
            {"key": "cholesterol", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "sodium", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "total_carbs", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "dietary_fiber", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "total_sugars", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "added_sugars", "is_mandatory": False, "show_percent_dv": True, "is_bold": False, "indent_level": 2},
            {"key": "sugar_alcohol", "is_mandatory": False, "show_percent_dv": False, "is_bold": False, "indent_level": 1},
            {"key": "protein", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "vitamin_d", "is_mandatory": False, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "calcium", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "iron", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "potassium", "is_mandatory": False, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
        ],
    },
    {
        "name": "UK Traffic Light",
        "code": "uk_traffic_light",
        "category": "regulatory",
        "description": "UK Front-of-Pack Traffic Light labeling system",
        "region": "UK",
        "languages": ["en"],
        "display_modes": ["per_serving", "per_100g"],
        "daily_calorie_base": 2000,
        "energy_unit": "both",
        "sodium_display": "salt",
        "default_width": 500,
        "default_height": 200,
        "is_system": True,
        "typography": {
            "fontFamily": "Arial, sans-serif",
            "titleFontSize": 14,
            "bodyFontSize": 12,
        },
        "border_config": {
            "width": 0,
            "color": "transparent",
            "style": "none",
        },
        "color_scheme": {
            "background": "#ffffff",
            "text": "#000000",
            "lowColor": "#33a532",
            "mediumColor": "#f5a623",
            "highColor": "#d0021b",
        },
        "footnotes": [],
        "nutrients": [
            {"key": "calories", "is_mandatory": True, "show_percent_dv": True, "is_bold": True, "indent_level": 0},
            {"key": "total_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "saturated_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "total_sugars", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "salt", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
        ],
    },
    {
        "name": "EU Standard",
        "code": "eu_standard",
        "category": "regulatory",
        "description": "European Union standard nutrition declaration format",
        "region": "EU",
        "languages": ["en"],
        "display_modes": ["per_100g", "per_serving"],
        "daily_calorie_base": 2000,
        "energy_unit": "both",
        "sodium_display": "salt",
        "default_width": 400,
        "default_height": 500,
        "is_system": True,
        "typography": {
            "fontFamily": "Arial, sans-serif",
            "titleFontSize": 14,
            "bodyFontSize": 11,
            "footnoteSize": 8,
        },
        "border_config": {
            "width": 1,
            "color": "#000000",
            "style": "solid",
        },
        "footnotes": [
            {
                "text": "Reference intake of an average adult (8400 kJ / 2000 kcal)",
                "required": True,
            },
        ],
        "nutrients": [
            {"key": "calories", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "total_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "saturated_fat", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "total_carbs", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "total_sugars", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 1},
            {"key": "protein", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
            {"key": "salt", "is_mandatory": True, "show_percent_dv": True, "is_bold": False, "indent_level": 0},
        ],
    },
]
