"""
Nutrient definitions seed data
"""

NUTRIENT_DEFINITIONS = [
    # Energy
    {
        "key": "calories",
        "name_en": "Calories",
        "name_ar": "السعرات الحرارية",
        "name_hi": "कैलोरी",
        "name_zh": "卡路里",
        "unit": "kcal",
        "category": "energy",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 1,
    },
    {
        "key": "calories_from_fat",
        "name_en": "Calories from Fat",
        "name_ar": "السعرات من الدهون",
        "name_hi": "वसा से कैलोरी",
        "name_zh": "脂肪热量",
        "unit": "kcal",
        "category": "energy",
        "parent_key": "calories",
        "is_mandatory_global": False,
        "default_order": 2,
    },

    # Macronutrients - Fats
    {
        "key": "total_fat",
        "name_en": "Total Fat",
        "name_ar": "الدهون الكلية",
        "name_hi": "कुल वसा",
        "name_zh": "总脂肪",
        "unit": "g",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 10,
    },
    {
        "key": "saturated_fat",
        "name_en": "Saturated Fat",
        "name_ar": "الدهون المشبعة",
        "name_hi": "संतृप्त वसा",
        "name_zh": "饱和脂肪",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_fat",
        "is_mandatory_global": True,
        "default_order": 11,
    },
    {
        "key": "trans_fat",
        "name_en": "Trans Fat",
        "name_ar": "الدهون المتحولة",
        "name_hi": "ट्रांस वसा",
        "name_zh": "反式脂肪",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_fat",
        "is_mandatory_global": True,
        "default_order": 12,
    },
    {
        "key": "polyunsaturated_fat",
        "name_en": "Polyunsaturated Fat",
        "name_ar": "الدهون متعددة اللاتشبع",
        "name_hi": "बहुअसंतृप्त वसा",
        "name_zh": "多不饱和脂肪",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_fat",
        "is_mandatory_global": False,
        "default_order": 13,
    },
    {
        "key": "monounsaturated_fat",
        "name_en": "Monounsaturated Fat",
        "name_ar": "الدهون أحادية اللاتشبع",
        "name_hi": "एकलअसंतृप्त वसा",
        "name_zh": "单不饱和脂肪",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_fat",
        "is_mandatory_global": False,
        "default_order": 14,
    },
    {
        "key": "cholesterol",
        "name_en": "Cholesterol",
        "name_ar": "الكوليسترول",
        "name_hi": "कोलेस्ट्रॉल",
        "name_zh": "胆固醇",
        "unit": "mg",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 20,
    },
    {
        "key": "sodium",
        "name_en": "Sodium",
        "name_ar": "الصوديوم",
        "name_hi": "सोडियम",
        "name_zh": "钠",
        "unit": "mg",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 30,
    },
    {
        "key": "salt",
        "name_en": "Salt",
        "name_ar": "الملح",
        "name_hi": "नमक",
        "name_zh": "盐",
        "unit": "g",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 31,
    },

    # Macronutrients - Carbohydrates
    {
        "key": "total_carbs",
        "name_en": "Total Carbohydrates",
        "name_ar": "الكربوهيدرات الكلية",
        "name_hi": "कुल कार्बोहाइड्रेट",
        "name_zh": "总碳水化合物",
        "unit": "g",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 40,
    },
    {
        "key": "dietary_fiber",
        "name_en": "Dietary Fiber",
        "name_ar": "الألياف الغذائية",
        "name_hi": "आहार फाइबर",
        "name_zh": "膳食纤维",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_carbs",
        "is_mandatory_global": True,
        "default_order": 41,
    },
    {
        "key": "total_sugars",
        "name_en": "Total Sugars",
        "name_ar": "السكريات الكلية",
        "name_hi": "कुल शर्करा",
        "name_zh": "总糖",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_carbs",
        "is_mandatory_global": True,
        "default_order": 42,
    },
    {
        "key": "added_sugars",
        "name_en": "Added Sugars",
        "name_ar": "السكريات المضافة",
        "name_hi": "जोड़ी गई शर्करा",
        "name_zh": "添加糖",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_sugars",
        "is_mandatory_global": True,
        "default_order": 43,
    },
    {
        "key": "sugar_alcohol",
        "name_en": "Sugar Alcohol",
        "name_ar": "كحول السكر",
        "name_hi": "शुगर अल्कोहल",
        "name_zh": "糖醇",
        "unit": "g",
        "category": "macro",
        "parent_key": "total_carbs",
        "is_mandatory_global": False,
        "default_order": 44,
    },

    # Protein
    {
        "key": "protein",
        "name_en": "Protein",
        "name_ar": "البروتين",
        "name_hi": "प्रोटीन",
        "name_zh": "蛋白质",
        "unit": "g",
        "category": "macro",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 50,
    },

    # Vitamins
    {
        "key": "vitamin_d",
        "name_en": "Vitamin D",
        "name_ar": "فيتامين د",
        "name_hi": "विटामिन डी",
        "name_zh": "维生素D",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 60,
    },
    {
        "key": "vitamin_a",
        "name_en": "Vitamin A",
        "name_ar": "فيتامين أ",
        "name_hi": "विटामिन ए",
        "name_zh": "维生素A",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 61,
    },
    {
        "key": "vitamin_c",
        "name_en": "Vitamin C",
        "name_ar": "فيتامين ج",
        "name_hi": "विटामिन सी",
        "name_zh": "维生素C",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 62,
    },
    {
        "key": "vitamin_e",
        "name_en": "Vitamin E",
        "name_ar": "فيتامين هـ",
        "name_hi": "विटामिन ई",
        "name_zh": "维生素E",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 63,
    },
    {
        "key": "vitamin_k",
        "name_en": "Vitamin K",
        "name_ar": "فيتامين ك",
        "name_hi": "विटामिन के",
        "name_zh": "维生素K",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 64,
    },
    {
        "key": "thiamin",
        "name_en": "Thiamin (B1)",
        "name_ar": "الثيامين (ب1)",
        "name_hi": "थायमिन (बी1)",
        "name_zh": "硫胺素 (B1)",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 65,
    },
    {
        "key": "riboflavin",
        "name_en": "Riboflavin (B2)",
        "name_ar": "الريبوفلافين (ب2)",
        "name_hi": "राइबोफ्लेविन (बी2)",
        "name_zh": "核黄素 (B2)",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 66,
    },
    {
        "key": "niacin",
        "name_en": "Niacin (B3)",
        "name_ar": "النياسين (ب3)",
        "name_hi": "नियासिन (बी3)",
        "name_zh": "烟酸 (B3)",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 67,
    },
    {
        "key": "vitamin_b6",
        "name_en": "Vitamin B6",
        "name_ar": "فيتامين ب6",
        "name_hi": "विटामिन बी6",
        "name_zh": "维生素B6",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 68,
    },
    {
        "key": "folate",
        "name_en": "Folate",
        "name_ar": "حمض الفوليك",
        "name_hi": "फोलेट",
        "name_zh": "叶酸",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 69,
    },
    {
        "key": "vitamin_b12",
        "name_en": "Vitamin B12",
        "name_ar": "فيتامين ب12",
        "name_hi": "विटामिन बी12",
        "name_zh": "维生素B12",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 70,
    },
    {
        "key": "biotin",
        "name_en": "Biotin",
        "name_ar": "البيوتين",
        "name_hi": "बायोटिन",
        "name_zh": "生物素",
        "unit": "mcg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 71,
    },
    {
        "key": "pantothenic_acid",
        "name_en": "Pantothenic Acid",
        "name_ar": "حمض البانتوثينيك",
        "name_hi": "पैंटोथेनिक एसिड",
        "name_zh": "泛酸",
        "unit": "mg",
        "category": "vitamin",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 72,
    },

    # Minerals
    {
        "key": "calcium",
        "name_en": "Calcium",
        "name_ar": "الكالسيوم",
        "name_hi": "कैल्शियम",
        "name_zh": "钙",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 80,
    },
    {
        "key": "iron",
        "name_en": "Iron",
        "name_ar": "الحديد",
        "name_hi": "लोहा",
        "name_zh": "铁",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 81,
    },
    {
        "key": "potassium",
        "name_en": "Potassium",
        "name_ar": "البوتاسيوم",
        "name_hi": "पोटेशियम",
        "name_zh": "钾",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": True,
        "default_order": 82,
    },
    {
        "key": "phosphorus",
        "name_en": "Phosphorus",
        "name_ar": "الفوسفور",
        "name_hi": "फास्फोरस",
        "name_zh": "磷",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 83,
    },
    {
        "key": "magnesium",
        "name_en": "Magnesium",
        "name_ar": "المغنيسيوم",
        "name_hi": "मैग्नीशियम",
        "name_zh": "镁",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 84,
    },
    {
        "key": "zinc",
        "name_en": "Zinc",
        "name_ar": "الزنك",
        "name_hi": "जस्ता",
        "name_zh": "锌",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 85,
    },
    {
        "key": "selenium",
        "name_en": "Selenium",
        "name_ar": "السيلينيوم",
        "name_hi": "सेलेनियम",
        "name_zh": "硒",
        "unit": "mcg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 86,
    },
    {
        "key": "copper",
        "name_en": "Copper",
        "name_ar": "النحاس",
        "name_hi": "तांबा",
        "name_zh": "铜",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 87,
    },
    {
        "key": "manganese",
        "name_en": "Manganese",
        "name_ar": "المنغنيز",
        "name_hi": "मैंगनीज",
        "name_zh": "锰",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 88,
    },
    {
        "key": "chromium",
        "name_en": "Chromium",
        "name_ar": "الكروم",
        "name_hi": "क्रोमियम",
        "name_zh": "铬",
        "unit": "mcg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 89,
    },
    {
        "key": "molybdenum",
        "name_en": "Molybdenum",
        "name_ar": "الموليبدينوم",
        "name_hi": "मोलिब्डेनम",
        "name_zh": "钼",
        "unit": "mcg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 90,
    },
    {
        "key": "chloride",
        "name_en": "Chloride",
        "name_ar": "الكلوريد",
        "name_hi": "क्लोराइड",
        "name_zh": "氯化物",
        "unit": "mg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 91,
    },
    {
        "key": "iodine",
        "name_en": "Iodine",
        "name_ar": "اليود",
        "name_hi": "आयोडीन",
        "name_zh": "碘",
        "unit": "mcg",
        "category": "mineral",
        "parent_key": None,
        "is_mandatory_global": False,
        "default_order": 92,
    },
]
