"""
RDA (Reference Daily Allowance) tables seed data
"""

from datetime import date

RDA_TABLES = [
    {
        "name": "FDA 2020",
        "code": "fda_2020",
        "description": "U.S. Food and Drug Administration Daily Values (2020 Update)",
        "region": "USA",
        "effective_date": date(2020, 1, 1),
        "calorie_base": 2000,
        "is_default": True,
        "values": {
            "total_fat": 78,
            "saturated_fat": 20,
            "trans_fat": None,  # No DV established
            "cholesterol": 300,
            "sodium": 2300,
            "total_carbs": 275,
            "dietary_fiber": 28,
            "total_sugars": None,  # No DV established
            "added_sugars": 50,
            "protein": 50,
            "vitamin_d": 20,
            "vitamin_a": 900,
            "vitamin_c": 90,
            "vitamin_e": 15,
            "vitamin_k": 120,
            "thiamin": 1.2,
            "riboflavin": 1.3,
            "niacin": 16,
            "vitamin_b6": 1.7,
            "folate": 400,
            "vitamin_b12": 2.4,
            "biotin": 30,
            "pantothenic_acid": 5,
            "calcium": 1300,
            "iron": 18,
            "potassium": 4700,
            "phosphorus": 1250,
            "magnesium": 420,
            "zinc": 11,
            "selenium": 55,
            "copper": 0.9,
            "manganese": 2.3,
            "chromium": 35,
            "molybdenum": 45,
            "chloride": 2300,
            "iodine": 150,
        },
        "units": {
            "total_fat": "g",
            "saturated_fat": "g",
            "trans_fat": "g",
            "cholesterol": "mg",
            "sodium": "mg",
            "total_carbs": "g",
            "dietary_fiber": "g",
            "added_sugars": "g",
            "protein": "g",
            "vitamin_d": "mcg",
            "vitamin_a": "mcg",
            "vitamin_c": "mg",
            "vitamin_e": "mg",
            "vitamin_k": "mcg",
            "thiamin": "mg",
            "riboflavin": "mg",
            "niacin": "mg",
            "vitamin_b6": "mg",
            "folate": "mcg",
            "vitamin_b12": "mcg",
            "biotin": "mcg",
            "pantothenic_acid": "mg",
            "calcium": "mg",
            "iron": "mg",
            "potassium": "mg",
            "phosphorus": "mg",
            "magnesium": "mg",
            "zinc": "mg",
            "selenium": "mcg",
            "copper": "mg",
            "manganese": "mg",
            "chromium": "mcg",
            "molybdenum": "mcg",
            "chloride": "mg",
            "iodine": "mcg",
        },
    },
    {
        "name": "GSO 2024",
        "code": "gso_2024",
        "description": "Gulf Cooperation Council Standardization Organization - GCC Food Labeling Requirements",
        "region": "GCC",
        "effective_date": date(2024, 1, 1),
        "calorie_base": 2000,
        "is_default": False,
        "values": {
            "total_fat": 70,
            "saturated_fat": 20,
            "trans_fat": None,
            "cholesterol": 300,
            "sodium": 2000,
            "salt": 5,  # GSO uses salt instead of sodium
            "total_carbs": 260,
            "dietary_fiber": 25,
            "total_sugars": 90,
            "added_sugars": 50,
            "protein": 50,
            "vitamin_d": 15,
            "vitamin_a": 800,
            "vitamin_c": 80,
            "vitamin_e": 12,
            "vitamin_k": 75,
            "thiamin": 1.1,
            "riboflavin": 1.4,
            "niacin": 16,
            "vitamin_b6": 1.4,
            "folate": 400,
            "vitamin_b12": 2.5,
            "biotin": 50,
            "pantothenic_acid": 6,
            "calcium": 1000,
            "iron": 14,
            "potassium": 4000,
            "phosphorus": 700,
            "magnesium": 375,
            "zinc": 10,
            "selenium": 55,
            "copper": 1,
            "manganese": 2,
            "chromium": 40,
            "molybdenum": 50,
            "chloride": 800,
            "iodine": 150,
        },
        "units": {
            "total_fat": "g",
            "saturated_fat": "g",
            "cholesterol": "mg",
            "sodium": "mg",
            "salt": "g",
            "total_carbs": "g",
            "dietary_fiber": "g",
            "total_sugars": "g",
            "added_sugars": "g",
            "protein": "g",
            "vitamin_d": "mcg",
            "vitamin_a": "mcg",
            "vitamin_c": "mg",
            "calcium": "mg",
            "iron": "mg",
            "potassium": "mg",
        },
    },
    {
        "name": "EU NRV",
        "code": "eu_nrv",
        "description": "European Union Nutrient Reference Values",
        "region": "EU",
        "effective_date": date(2011, 12, 1),
        "calorie_base": 2000,
        "is_default": False,
        "values": {
            "total_fat": 70,
            "saturated_fat": 20,
            "cholesterol": None,  # EU doesn't set DV for cholesterol
            "sodium": None,  # EU uses salt
            "salt": 6,
            "total_carbs": 260,
            "dietary_fiber": None,  # EU doesn't mandate fiber DV
            "total_sugars": 90,
            "protein": 50,
            "vitamin_d": 5,
            "vitamin_a": 800,
            "vitamin_c": 80,
            "vitamin_e": 12,
            "vitamin_k": 75,
            "thiamin": 1.1,
            "riboflavin": 1.4,
            "niacin": 16,
            "vitamin_b6": 1.4,
            "folate": 200,
            "vitamin_b12": 2.5,
            "biotin": 50,
            "pantothenic_acid": 6,
            "calcium": 800,
            "iron": 14,
            "potassium": 2000,
            "phosphorus": 700,
            "magnesium": 375,
            "zinc": 10,
            "selenium": 55,
            "copper": 1,
            "manganese": 2,
            "chromium": 40,
            "molybdenum": 50,
            "chloride": 800,
            "iodine": 150,
        },
        "units": {
            "total_fat": "g",
            "saturated_fat": "g",
            "salt": "g",
            "total_carbs": "g",
            "total_sugars": "g",
            "protein": "g",
            "vitamin_d": "mcg",
            "vitamin_a": "mcg",
            "vitamin_c": "mg",
            "calcium": "mg",
            "iron": "mg",
            "potassium": "mg",
        },
    },
]
